theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  persons:
    single:
      backlinks: true
  posts:
    index:
      layout: grid
  organizations:
    single:
      backlinks: true
  search:
    active: true
  summary:
    position: hero
  home:
    head:
      title: site